apiVersion: apps/v1
kind: Deployment
metadata:
  name: zippyurl-deployment
  labels:
    app: zippyurl
  namespace: devsquad
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zippyurl
  template:
    metadata:
      labels:
        app: zippyurl
    spec:
      containers:
      - name: zippyurl
        image: lekhanag240304/zippy_url:latest
        ports:
        - containerPort: 3000
