apiVersion: v1
kind: Service
metadata:
  name: zippyurl-service
  namespace: devsquad
spec:
  selector:
    app: zippyurl
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5276
    targetPort: 3000
    nodePort: 32005
